const narutoEpSelect = document.getElementById('naruto-episode-selection')
const shippuudenEpSelect = document.getElementById('shippuuden-episode-selection')

const buttons = document.querySelectorAll('.series-button')
buttons.forEach(button => button.addEventListener('click', showSeries))

function showSeries() {
  switch(this.name) {
    case 'naruto':
    narutoEpSelect.classList.add('active-series')
    shippuudenEpSelect.classList.remove('active-series')
    break;
    case 'shippuuden':
    shippuudenEpSelect.classList.add('active-series')
    narutoEpSelect.classList.remove('active-series')
    break;
    default:
    lastSelectedTable = ''
    return;
  }
}
/*
case 'ns1':
lastSelectedButton = this.name
document.querySelector('.naruto-season-1-table').style.display = 'flex'
document.querySelector('.naruto-season-2-table').style.display = 'none'
document.querySelector('.naruto-season-3-table').style.display = 'none'
document.querySelector('.naruto-season-4-table').style.display = 'none'
document.querySelector('.naruto-season-5-table').style.display = 'none'
document.querySelector('.naruto-season-6-table').style.display = 'none'
document.querySelector('.naruto-season-7-table').style.display = 'none'
document.querySelector('.naruto-season-8-table').style.display = 'none'
document.querySelector('.naruto-season-9-table').style.display = 'none'
document.querySelector('.naruto-movies-table').style.display = 'none'
break;
case 'ns2':
lastSelectedButton = this.name
document.querySelector('.naruto-season-2-table').style.display = 'flex'
document.querySelector('.naruto-season-1-table').style.display = 'none'
document.querySelector('.naruto-season-3-table').style.display = 'none'
document.querySelector('.naruto-season-4-table').style.display = 'none'
document.querySelector('.naruto-season-5-table').style.display = 'none'
document.querySelector('.naruto-season-6-table').style.display = 'none'
document.querySelector('.naruto-season-7-table').style.display = 'none'
document.querySelector('.naruto-season-8-table').style.display = 'none'
document.querySelector('.naruto-season-9-table').style.display = 'none'
document.querySelector('.naruto-movies-table').style.display = 'none'
break;
case 'ns3':
lastSelectedButton = this.name
document.querySelector('.naruto-season-3-table').style.display = 'flex'
document.querySelector('.naruto-season-1-table').style.display = 'none'
document.querySelector('.naruto-season-2-table').style.display = 'none'
document.querySelector('.naruto-season-4-table').style.display = 'none'
document.querySelector('.naruto-season-5-table').style.display = 'none'
document.querySelector('.naruto-season-6-table').style.display = 'none'
document.querySelector('.naruto-season-7-table').style.display = 'none'
document.querySelector('.naruto-season-8-table').style.display = 'none'
document.querySelector('.naruto-season-9-table').style.display = 'none'
document.querySelector('.naruto-movies-table').style.display = 'none'
break;
case 'ns4':
lastSelectedButton = this.name
document.querySelector('.naruto-season-4-table').style.display = 'flex'
document.querySelector('.naruto-season-1-table').style.display = 'none'
document.querySelector('.naruto-season-2-table').style.display = 'none'
document.querySelector('.naruto-season-3-table').style.display = 'none'
document.querySelector('.naruto-season-5-table').style.display = 'none'
document.querySelector('.naruto-season-6-table').style.display = 'none'
document.querySelector('.naruto-season-7-table').style.display = 'none'
document.querySelector('.naruto-season-8-table').style.display = 'none'
document.querySelector('.naruto-season-9-table').style.display = 'none'
document.querySelector('.naruto-movies-table').style.display = 'none'
break;
case 'ns5':
lastSelectedButton = this.name
document.querySelector('.naruto-season-5-table').style.display = 'flex'
document.querySelector('.naruto-season-1-table').style.display = 'none'
document.querySelector('.naruto-season-2-table').style.display = 'none'
document.querySelector('.naruto-season-3-table').style.display = 'none'
document.querySelector('.naruto-season-4-table').style.display = 'none'
document.querySelector('.naruto-season-6-table').style.display = 'none'
document.querySelector('.naruto-season-7-table').style.display = 'none'
document.querySelector('.naruto-season-8-table').style.display = 'none'
document.querySelector('.naruto-season-9-table').style.display = 'none'
document.querySelector('.naruto-movies-table').style.display = 'none'
break;
case 'ns6':
lastSelectedButton = this.name
document.querySelector('.naruto-season-6-table').style.display = 'flex'
document.querySelector('.naruto-season-1-table').style.display = 'none'
document.querySelector('.naruto-season-2-table').style.display = 'none'
document.querySelector('.naruto-season-3-table').style.display = 'none'
document.querySelector('.naruto-season-4-table').style.display = 'none'
document.querySelector('.naruto-season-5-table').style.display = 'none'
document.querySelector('.naruto-season-7-table').style.display = 'none'
document.querySelector('.naruto-season-8-table').style.display = 'none'
document.querySelector('.naruto-season-9-table').style.display = 'none'
document.querySelector('.naruto-movies-table').style.display = 'none'
break;
case 'ns7':
lastSelectedButton = this.name
document.querySelector('.naruto-season-7-table').style.display = 'flex'
document.querySelector('.naruto-season-1-table').style.display = 'none'
document.querySelector('.naruto-season-2-table').style.display = 'none'
document.querySelector('.naruto-season-3-table').style.display = 'none'
document.querySelector('.naruto-season-4-table').style.display = 'none'
document.querySelector('.naruto-season-5-table').style.display = 'none'
document.querySelector('.naruto-season-6-table').style.display = 'none'
document.querySelector('.naruto-season-8-table').style.display = 'none'
document.querySelector('.naruto-season-9-table').style.display = 'none'
document.querySelector('.naruto-movies-table').style.display = 'none'
break;
case 'ns8':
lastSelectedButton = this.name
document.querySelector('.naruto-season-8-table').style.display = 'flex'
document.querySelector('.naruto-season-1-table').style.display = 'none'
document.querySelector('.naruto-season-2-table').style.display = 'none'
document.querySelector('.naruto-season-3-table').style.display = 'none'
document.querySelector('.naruto-season-4-table').style.display = 'none'
document.querySelector('.naruto-season-5-table').style.display = 'none'
document.querySelector('.naruto-season-6-table').style.display = 'none'
document.querySelector('.naruto-season-7-table').style.display = 'none'
document.querySelector('.naruto-season-9-table').style.display = 'none'
document.querySelector('.naruto-movies-table').style.display = 'none'
break;
case 'ns9':
lastSelectedButton = this.name
document.querySelector('.naruto-season-9-table').style.display = 'flex'
document.querySelector('.naruto-season-1-table').style.display = 'none'
document.querySelector('.naruto-season-2-table').style.display = 'none'
document.querySelector('.naruto-season-3-table').style.display = 'none'
document.querySelector('.naruto-season-4-table').style.display = 'none'
document.querySelector('.naruto-season-5-table').style.display = 'none'
document.querySelector('.naruto-season-6-table').style.display = 'none'
document.querySelector('.naruto-season-7-table').style.display = 'none'
document.querySelector('.naruto-season-8-table').style.display = 'none'
document.querySelector('.naruto-movies-table').style.display = 'none'
break;
case 'nsm':
lastSelectedButton = this.name
document.querySelector('.naruto-movies-table').style.display = 'flex'
document.querySelector('.naruto-season-1-table').style.display = 'none'
document.querySelector('.naruto-season-2-table').style.display = 'none'
document.querySelector('.naruto-season-3-table').style.display = 'none'
document.querySelector('.naruto-season-4-table').style.display = 'none'
document.querySelector('.naruto-season-5-table').style.display = 'none'
document.querySelector('.naruto-season-6-table').style.display = 'none'
document.querySelector('.naruto-season-7-table').style.display = 'none'
document.querySelector('.naruto-season-8-table').style.display = 'none'
document.querySelector('.naruto-season-9-table').style.display = 'none'
break;
case 'ss1':
lastSelectedButton = this.name
document.querySelector('.shippuuden-season-1-table').style.display = 'flex'
document.querySelector('.shippuuden-season-2-table').style.display = 'none'
document.querySelector('.shippuuden-season-3-table').style.display = 'none'
document.querySelector('.shippuuden-season-4-table').style.display = 'none'
document.querySelector('.shippuuden-season-5-table').style.display = 'none'
document.querySelector('.shippuuden-season-6-table').style.display = 'none'
document.querySelector('.shippuuden-season-7-table').style.display = 'none'
document.querySelector('.shippuuden-season-8-table').style.display = 'none'
document.querySelector('.shippuuden-season-9-table').style.display = 'none'
document.querySelector('.shippuuden-season-10-table').style.display = 'none'
document.querySelector('.shippuuden-season-11-table').style.display = 'none'
document.querySelector('.shippuuden-season-12-table').style.display = 'none'
document.querySelector('.shippuuden-season-13-table').style.display = 'none'
document.querySelector('.shippuuden-season-14-table').style.display = 'none'
document.querySelector('.shippuuden-season-15-table').style.display = 'none'
document.querySelector('.shippuuden-season-16-table').style.display = 'none'
document.querySelector('.shippuuden-season-17-table').style.display = 'none'
document.querySelector('.shippuuden-season-18-table').style.display = 'none'
document.querySelector('.shippuuden-season-19-table').style.display = 'none'
document.querySelector('.shippuuden-season-20-table').style.display = 'none'
document.querySelector('.shippuuden-season-21-table').style.display = 'none'
document.querySelector('.shippuuden-movies-table').style.display = 'none'
break;
case 'ss2':
lastSelectedButton = this.name
document.querySelector('.shippuuden-season-2-table').style.display = 'flex'
document.querySelector('.shippuuden-season-1-table').style.display = 'none'
document.querySelector('.shippuuden-season-3-table').style.display = 'none'
document.querySelector('.shippuuden-season-4-table').style.display = 'none'
document.querySelector('.shippuuden-season-5-table').style.display = 'none'
document.querySelector('.shippuuden-season-6-table').style.display = 'none'
document.querySelector('.shippuuden-season-7-table').style.display = 'none'
document.querySelector('.shippuuden-season-8-table').style.display = 'none'
document.querySelector('.shippuuden-season-9-table').style.display = 'none'
document.querySelector('.shippuuden-season-10-table').style.display = 'none'
document.querySelector('.shippuuden-season-11-table').style.display = 'none'
document.querySelector('.shippuuden-season-12-table').style.display = 'none'
document.querySelector('.shippuuden-season-13-table').style.display = 'none'
document.querySelector('.shippuuden-season-14-table').style.display = 'none'
document.querySelector('.shippuuden-season-15-table').style.display = 'none'
document.querySelector('.shippuuden-season-16-table').style.display = 'none'
document.querySelector('.shippuuden-season-17-table').style.display = 'none'
document.querySelector('.shippuuden-season-18-table').style.display = 'none'
document.querySelector('.shippuuden-season-19-table').style.display = 'none'
document.querySelector('.shippuuden-season-20-table').style.display = 'none'
document.querySelector('.shippuuden-season-21-table').style.display = 'none'
document.querySelector('.shippuuden-movies-table').style.display = 'none'
break;
case 'ss3':
lastSelectedButton = this.name
document.querySelector('.shippuuden-season-3-table').style.display = 'flex'
document.querySelector('.shippuuden-season-1-table').style.display = 'none'
document.querySelector('.shippuuden-season-2-table').style.display = 'none'
document.querySelector('.shippuuden-season-4-table').style.display = 'none'
document.querySelector('.shippuuden-season-5-table').style.display = 'none'
document.querySelector('.shippuuden-season-6-table').style.display = 'none'
document.querySelector('.shippuuden-season-7-table').style.display = 'none'
document.querySelector('.shippuuden-season-8-table').style.display = 'none'
document.querySelector('.shippuuden-season-9-table').style.display = 'none'
document.querySelector('.shippuuden-season-10-table').style.display = 'none'
document.querySelector('.shippuuden-season-11-table').style.display = 'none'
document.querySelector('.shippuuden-season-12-table').style.display = 'none'
document.querySelector('.shippuuden-season-13-table').style.display = 'none'
document.querySelector('.shippuuden-season-14-table').style.display = 'none'
document.querySelector('.shippuuden-season-15-table').style.display = 'none'
document.querySelector('.shippuuden-season-16-table').style.display = 'none'
document.querySelector('.shippuuden-season-17-table').style.display = 'none'
document.querySelector('.shippuuden-season-18-table').style.display = 'none'
document.querySelector('.shippuuden-season-19-table').style.display = 'none'
document.querySelector('.shippuuden-season-20-table').style.display = 'none'
document.querySelector('.shippuuden-season-21-table').style.display = 'none'
document.querySelector('.shippuuden-movies-table').style.display = 'none'
break;
case 'ss4':
lastSelectedButton = this.name
document.querySelector('.shippuuden-season-4-table').style.display = 'flex'
document.querySelector('.shippuuden-season-1-table').style.display = 'none'
document.querySelector('.shippuuden-season-2-table').style.display = 'none'
document.querySelector('.shippuuden-season-3-table').style.display = 'none'
document.querySelector('.shippuuden-season-5-table').style.display = 'none'
document.querySelector('.shippuuden-season-6-table').style.display = 'none'
document.querySelector('.shippuuden-season-7-table').style.display = 'none'
document.querySelector('.shippuuden-season-8-table').style.display = 'none'
document.querySelector('.shippuuden-season-9-table').style.display = 'none'
document.querySelector('.shippuuden-season-10-table').style.display = 'none'
document.querySelector('.shippuuden-season-11-table').style.display = 'none'
document.querySelector('.shippuuden-season-12-table').style.display = 'none'
document.querySelector('.shippuuden-season-13-table').style.display = 'none'
document.querySelector('.shippuuden-season-14-table').style.display = 'none'
document.querySelector('.shippuuden-season-15-table').style.display = 'none'
document.querySelector('.shippuuden-season-16-table').style.display = 'none'
document.querySelector('.shippuuden-season-17-table').style.display = 'none'
document.querySelector('.shippuuden-season-18-table').style.display = 'none'
document.querySelector('.shippuuden-season-19-table').style.display = 'none'
document.querySelector('.shippuuden-season-20-table').style.display = 'none'
document.querySelector('.shippuuden-season-21-table').style.display = 'none'
document.querySelector('.shippuuden-movies-table').style.display = 'none'
break;
case 'ss5':
lastSelectedButton = this.name
document.querySelector('.shippuuden-season-5-table').style.display = 'flex'
document.querySelector('.shippuuden-season-1-table').style.display = 'none'
document.querySelector('.shippuuden-season-2-table').style.display = 'none'
document.querySelector('.shippuuden-season-3-table').style.display = 'none'
document.querySelector('.shippuuden-season-4-table').style.display = 'none'
document.querySelector('.shippuuden-season-6-table').style.display = 'none'
document.querySelector('.shippuuden-season-7-table').style.display = 'none'
document.querySelector('.shippuuden-season-8-table').style.display = 'none'
document.querySelector('.shippuuden-season-9-table').style.display = 'none'
document.querySelector('.shippuuden-season-10-table').style.display = 'none'
document.querySelector('.shippuuden-season-11-table').style.display = 'none'
document.querySelector('.shippuuden-season-12-table').style.display = 'none'
document.querySelector('.shippuuden-season-13-table').style.display = 'none'
document.querySelector('.shippuuden-season-14-table').style.display = 'none'
document.querySelector('.shippuuden-season-15-table').style.display = 'none'
document.querySelector('.shippuuden-season-16-table').style.display = 'none'
document.querySelector('.shippuuden-season-17-table').style.display = 'none'
document.querySelector('.shippuuden-season-18-table').style.display = 'none'
document.querySelector('.shippuuden-season-19-table').style.display = 'none'
document.querySelector('.shippuuden-season-20-table').style.display = 'none'
document.querySelector('.shippuuden-season-21-table').style.display = 'none'
document.querySelector('.shippuuden-movies-table').style.display = 'none'
break;
case 'ss6':
lastSelectedButton = this.name
document.querySelector('.shippuuden-season-6-table').style.display = 'flex'
document.querySelector('.shippuuden-season-1-table').style.display = 'none'
document.querySelector('.shippuuden-season-2-table').style.display = 'none'
document.querySelector('.shippuuden-season-3-table').style.display = 'none'
document.querySelector('.shippuuden-season-4-table').style.display = 'none'
document.querySelector('.shippuuden-season-5-table').style.display = 'none'
document.querySelector('.shippuuden-season-7-table').style.display = 'none'
document.querySelector('.shippuuden-season-8-table').style.display = 'none'
document.querySelector('.shippuuden-season-9-table').style.display = 'none'
document.querySelector('.shippuuden-season-10-table').style.display = 'none'
document.querySelector('.shippuuden-season-11-table').style.display = 'none'
document.querySelector('.shippuuden-season-12-table').style.display = 'none'
document.querySelector('.shippuuden-season-13-table').style.display = 'none'
document.querySelector('.shippuuden-season-14-table').style.display = 'none'
document.querySelector('.shippuuden-season-15-table').style.display = 'none'
document.querySelector('.shippuuden-season-16-table').style.display = 'none'
document.querySelector('.shippuuden-season-17-table').style.display = 'none'
document.querySelector('.shippuuden-season-18-table').style.display = 'none'
document.querySelector('.shippuuden-season-19-table').style.display = 'none'
document.querySelector('.shippuuden-season-20-table').style.display = 'none'
document.querySelector('.shippuuden-season-21-table').style.display = 'none'
document.querySelector('.shippuuden-movies-table').style.display = 'none'
break;
case 'ss7':
lastSelectedButton = this.name
document.querySelector('.shippuuden-season-7-table').style.display = 'flex'
document.querySelector('.shippuuden-season-1-table').style.display = 'none'
document.querySelector('.shippuuden-season-2-table').style.display = 'none'
document.querySelector('.shippuuden-season-3-table').style.display = 'none'
document.querySelector('.shippuuden-season-4-table').style.display = 'none'
document.querySelector('.shippuuden-season-5-table').style.display = 'none'
document.querySelector('.shippuuden-season-6-table').style.display = 'none'
document.querySelector('.shippuuden-season-8-table').style.display = 'none'
document.querySelector('.shippuuden-season-9-table').style.display = 'none'
document.querySelector('.shippuuden-season-10-table').style.display = 'none'
document.querySelector('.shippuuden-season-11-table').style.display = 'none'
document.querySelector('.shippuuden-season-12-table').style.display = 'none'
document.querySelector('.shippuuden-season-13-table').style.display = 'none'
document.querySelector('.shippuuden-season-14-table').style.display = 'none'
document.querySelector('.shippuuden-season-15-table').style.display = 'none'
document.querySelector('.shippuuden-season-16-table').style.display = 'none'
document.querySelector('.shippuuden-season-17-table').style.display = 'none'
document.querySelector('.shippuuden-season-18-table').style.display = 'none'
document.querySelector('.shippuuden-season-19-table').style.display = 'none'
document.querySelector('.shippuuden-season-20-table').style.display = 'none'
document.querySelector('.shippuuden-season-21-table').style.display = 'none'
document.querySelector('.shippuuden-movies-table').style.display = 'none'
break;
case 'ss8':
lastSelectedButton = this.name
document.querySelector('.shippuuden-season-8-table').style.display = 'flex'
document.querySelector('.shippuuden-season-1-table').style.display = 'none'
document.querySelector('.shippuuden-season-2-table').style.display = 'none'
document.querySelector('.shippuuden-season-3-table').style.display = 'none'
document.querySelector('.shippuuden-season-4-table').style.display = 'none'
document.querySelector('.shippuuden-season-5-table').style.display = 'none'
document.querySelector('.shippuuden-season-6-table').style.display = 'none'
document.querySelector('.shippuuden-season-7-table').style.display = 'none'
document.querySelector('.shippuuden-season-9-table').style.display = 'none'
document.querySelector('.shippuuden-season-10-table').style.display = 'none'
document.querySelector('.shippuuden-season-11-table').style.display = 'none'
document.querySelector('.shippuuden-season-12-table').style.display = 'none'
document.querySelector('.shippuuden-season-13-table').style.display = 'none'
document.querySelector('.shippuuden-season-14-table').style.display = 'none'
document.querySelector('.shippuuden-season-15-table').style.display = 'none'
document.querySelector('.shippuuden-season-16-table').style.display = 'none'
document.querySelector('.shippuuden-season-17-table').style.display = 'none'
document.querySelector('.shippuuden-season-18-table').style.display = 'none'
document.querySelector('.shippuuden-season-19-table').style.display = 'none'
document.querySelector('.shippuuden-season-20-table').style.display = 'none'
document.querySelector('.shippuuden-season-21-table').style.display = 'none'
document.querySelector('.shippuuden-movies-table').style.display = 'none'
break;
case 'ss9':
lastSelectedButton = this.name
document.querySelector('.shippuuden-season-9-table').style.display = 'flex'
document.querySelector('.shippuuden-season-1-table').style.display = 'none'
document.querySelector('.shippuuden-season-2-table').style.display = 'none'
document.querySelector('.shippuuden-season-3-table').style.display = 'none'
document.querySelector('.shippuuden-season-4-table').style.display = 'none'
document.querySelector('.shippuuden-season-5-table').style.display = 'none'
document.querySelector('.shippuuden-season-6-table').style.display = 'none'
document.querySelector('.shippuuden-season-7-table').style.display = 'none'
document.querySelector('.shippuuden-season-8-table').style.display = 'none'
document.querySelector('.shippuuden-season-10-table').style.display = 'none'
document.querySelector('.shippuuden-season-11-table').style.display = 'none'
document.querySelector('.shippuuden-season-12-table').style.display = 'none'
document.querySelector('.shippuuden-season-13-table').style.display = 'none'
document.querySelector('.shippuuden-season-14-table').style.display = 'none'
document.querySelector('.shippuuden-season-15-table').style.display = 'none'
document.querySelector('.shippuuden-season-16-table').style.display = 'none'
document.querySelector('.shippuuden-season-17-table').style.display = 'none'
document.querySelector('.shippuuden-season-18-table').style.display = 'none'
document.querySelector('.shippuuden-season-19-table').style.display = 'none'
document.querySelector('.shippuuden-season-20-table').style.display = 'none'
document.querySelector('.shippuuden-season-21-table').style.display = 'none'
document.querySelector('.shippuuden-movies-table').style.display = 'none'
break;
case 'ss10':
lastSelectedButton = this.name
document.querySelector('.shippuuden-season-10-table').style.display = 'flex'
document.querySelector('.shippuuden-season-1-table').style.display = 'none'
document.querySelector('.shippuuden-season-2-table').style.display = 'none'
document.querySelector('.shippuuden-season-3-table').style.display = 'none'
document.querySelector('.shippuuden-season-4-table').style.display = 'none'
document.querySelector('.shippuuden-season-5-table').style.display = 'none'
document.querySelector('.shippuuden-season-6-table').style.display = 'none'
document.querySelector('.shippuuden-season-7-table').style.display = 'none'
document.querySelector('.shippuuden-season-8-table').style.display = 'none'
document.querySelector('.shippuuden-season-9-table').style.display = 'none'
document.querySelector('.shippuuden-season-11-table').style.display = 'none'
document.querySelector('.shippuuden-season-12-table').style.display = 'none'
document.querySelector('.shippuuden-season-13-table').style.display = 'none'
document.querySelector('.shippuuden-season-14-table').style.display = 'none'
document.querySelector('.shippuuden-season-15-table').style.display = 'none'
document.querySelector('.shippuuden-season-16-table').style.display = 'none'
document.querySelector('.shippuuden-season-17-table').style.display = 'none'
document.querySelector('.shippuuden-season-18-table').style.display = 'none'
document.querySelector('.shippuuden-season-19-table').style.display = 'none'
document.querySelector('.shippuuden-season-20-table').style.display = 'none'
document.querySelector('.shippuuden-season-21-table').style.display = 'none'
document.querySelector('.shippuuden-movies-table').style.display = 'none'
break;
case 'ss11':
lastSelectedButton = this.name
document.querySelector('.shippuuden-season-11-table').style.display = 'flex'
document.querySelector('.shippuuden-season-1-table').style.display = 'none'
document.querySelector('.shippuuden-season-2-table').style.display = 'none'
document.querySelector('.shippuuden-season-3-table').style.display = 'none'
document.querySelector('.shippuuden-season-4-table').style.display = 'none'
document.querySelector('.shippuuden-season-5-table').style.display = 'none'
document.querySelector('.shippuuden-season-6-table').style.display = 'none'
document.querySelector('.shippuuden-season-7-table').style.display = 'none'
document.querySelector('.shippuuden-season-8-table').style.display = 'none'
document.querySelector('.shippuuden-season-9-table').style.display = 'none'
document.querySelector('.shippuuden-season-10-table').style.display = 'none'
document.querySelector('.shippuuden-season-12-table').style.display = 'none'
document.querySelector('.shippuuden-season-13-table').style.display = 'none'
document.querySelector('.shippuuden-season-14-table').style.display = 'none'
document.querySelector('.shippuuden-season-15-table').style.display = 'none'
document.querySelector('.shippuuden-season-16-table').style.display = 'none'
document.querySelector('.shippuuden-season-17-table').style.display = 'none'
document.querySelector('.shippuuden-season-18-table').style.display = 'none'
document.querySelector('.shippuuden-season-19-table').style.display = 'none'
document.querySelector('.shippuuden-season-20-table').style.display = 'none'
document.querySelector('.shippuuden-season-21-table').style.display = 'none'
document.querySelector('.shippuuden-movies-table').style.display = 'none'
break;
case 'ss12':
lastSelectedButton = this.name
document.querySelector('.shippuuden-season-12-table').style.display = 'flex'
document.querySelector('.shippuuden-season-1-table').style.display = 'none'
document.querySelector('.shippuuden-season-2-table').style.display = 'none'
document.querySelector('.shippuuden-season-3-table').style.display = 'none'
document.querySelector('.shippuuden-season-4-table').style.display = 'none'
document.querySelector('.shippuuden-season-5-table').style.display = 'none'
document.querySelector('.shippuuden-season-6-table').style.display = 'none'
document.querySelector('.shippuuden-season-7-table').style.display = 'none'
document.querySelector('.shippuuden-season-8-table').style.display = 'none'
document.querySelector('.shippuuden-season-9-table').style.display = 'none'
document.querySelector('.shippuuden-season-10-table').style.display = 'none'
document.querySelector('.shippuuden-season-11-table').style.display = 'none'
document.querySelector('.shippuuden-season-13-table').style.display = 'none'
document.querySelector('.shippuuden-season-14-table').style.display = 'none'
document.querySelector('.shippuuden-season-15-table').style.display = 'none'
document.querySelector('.shippuuden-season-16-table').style.display = 'none'
document.querySelector('.shippuuden-season-17-table').style.display = 'none'
document.querySelector('.shippuuden-season-18-table').style.display = 'none'
document.querySelector('.shippuuden-season-19-table').style.display = 'none'
document.querySelector('.shippuuden-season-20-table').style.display = 'none'
document.querySelector('.shippuuden-season-21-table').style.display = 'none'
document.querySelector('.shippuuden-movies-table').style.display = 'none'
break;
case 'ss13':
lastSelectedButton = this.name
document.querySelector('.shippuuden-season-13-table').style.display = 'flex'
document.querySelector('.shippuuden-season-1-table').style.display = 'none'
document.querySelector('.shippuuden-season-2-table').style.display = 'none'
document.querySelector('.shippuuden-season-3-table').style.display = 'none'
document.querySelector('.shippuuden-season-4-table').style.display = 'none'
document.querySelector('.shippuuden-season-5-table').style.display = 'none'
document.querySelector('.shippuuden-season-6-table').style.display = 'none'
document.querySelector('.shippuuden-season-7-table').style.display = 'none'
document.querySelector('.shippuuden-season-8-table').style.display = 'none'
document.querySelector('.shippuuden-season-9-table').style.display = 'none'
document.querySelector('.shippuuden-season-10-table').style.display = 'none'
document.querySelector('.shippuuden-season-11-table').style.display = 'none'
document.querySelector('.shippuuden-season-12-table').style.display = 'none'
document.querySelector('.shippuuden-season-14-table').style.display = 'none'
document.querySelector('.shippuuden-season-15-table').style.display = 'none'
document.querySelector('.shippuuden-season-16-table').style.display = 'none'
document.querySelector('.shippuuden-season-17-table').style.display = 'none'
document.querySelector('.shippuuden-season-18-table').style.display = 'none'
document.querySelector('.shippuuden-season-19-table').style.display = 'none'
document.querySelector('.shippuuden-season-20-table').style.display = 'none'
document.querySelector('.shippuuden-season-21-table').style.display = 'none'
document.querySelector('.shippuuden-movies-table').style.display = 'none'
break;
case 'ss14':
lastSelectedButton = this.name
document.querySelector('.shippuuden-season-14-table').style.display = 'flex'
document.querySelector('.shippuuden-season-1-table').style.display = 'none'
document.querySelector('.shippuuden-season-2-table').style.display = 'none'
document.querySelector('.shippuuden-season-3-table').style.display = 'none'
document.querySelector('.shippuuden-season-4-table').style.display = 'none'
document.querySelector('.shippuuden-season-5-table').style.display = 'none'
document.querySelector('.shippuuden-season-6-table').style.display = 'none'
document.querySelector('.shippuuden-season-7-table').style.display = 'none'
document.querySelector('.shippuuden-season-8-table').style.display = 'none'
document.querySelector('.shippuuden-season-9-table').style.display = 'none'
document.querySelector('.shippuuden-season-10-table').style.display = 'none'
document.querySelector('.shippuuden-season-11.table').style.display = 'none'
document.querySelector('.shippuuden-season-12-table').style.display = 'none'
document.querySelector('.shippuuden-season-13-table').style.display = 'none'
document.querySelector('.shippuuden-season-15-table').style.display = 'none'
document.querySelector('.shippuuden-season-16-table').style.display = 'none'
document.querySelector('.shippuuden-season-17-table').style.display = 'none'
document.querySelector('.shippuuden-season-18-table').style.display = 'none'
document.querySelector('.shippuuden-season-19-table').style.display = 'none'
document.querySelector('.shippuuden-season-20-table').style.display = 'none'
document.querySelector('.shippuuden-season-21-table').style.display = 'none'
document.querySelector('.shippuuden-movies-table').style.display = 'none'
break;
case 'ss15':
lastSelectedButton = this.name
document.querySelector('.shippuuden-season-15-table').style.display = 'flex'
document.querySelector('.shippuuden-season-1-table').style.display = 'none'
document.querySelector('.shippuuden-season-2-table').style.display = 'none'
document.querySelector('.shippuuden-season-3-table').style.display = 'none'
document.querySelector('.shippuuden-season-4-table').style.display = 'none'
document.querySelector('.shippuuden-season-5-table').style.display = 'none'
document.querySelector('.shippuuden-season-6-table').style.display = 'none'
document.querySelector('.shippuuden-season-7-table').style.display = 'none'
document.querySelector('.shippuuden-season-8-table').style.display = 'none'
document.querySelector('.shippuuden-season-9-table').style.display = 'none'
document.querySelector('.shippuuden-season-10-table').style.display = 'none'
document.querySelector('.shippuuden-season-11-table').style.display = 'none'
document.querySelector('.shippuuden-season-12-table').style.display = 'none'
document.querySelector('.shippuuden-season-13-table').style.display = 'none'
document.querySelector('.shippuuden-season-14-table').style.display = 'none'
document.querySelector('.shippuuden-season-16-table').style.display = 'none'
document.querySelector('.shippuuden-season-17-table').style.display = 'none'
document.querySelector('.shippuuden-season-18-table').style.display = 'none'
document.querySelector('.shippuuden-season-19-table').style.display = 'none'
document.querySelector('.shippuuden-season-20-table').style.display = 'none'
document.querySelector('.shippuuden-season-21-table').style.display = 'none'
document.querySelector('.shippuuden-movies-table').style.display = 'none'
break;
case 'ss16':
lastSelectedButton = this.name
document.querySelector('.shippuuden-season-16-table').style.display = 'flex'
document.querySelector('.shippuuden-season-1-table').style.display = 'none'
document.querySelector('.shippuuden-season-2-table').style.display = 'none'
document.querySelector('.shippuuden-season-3-table').style.display = 'none'
document.querySelector('.shippuuden-season-4-table').style.display = 'none'
document.querySelector('.shippuuden-season-5-table').style.display = 'none'
document.querySelector('.shippuuden-season-6-table').style.display = 'none'
document.querySelector('.shippuuden-season-7-table').style.display = 'none'
document.querySelector('.shippuuden-season-8-table').style.display = 'none'
document.querySelector('.shippuuden-season-9-table').style.display = 'none'
document.querySelector('.shippuuden-season-10-table').style.display = 'none'
document.querySelector('.shippuuden-season-11-table').style.display = 'none'
document.querySelector('.shippuuden-season-12-table').style.display = 'none'
document.querySelector('.shippuuden-season-13-table').style.display = 'none'
document.querySelector('.shippuuden-season-14-table').style.display = 'none'
document.querySelector('.shippuuden-season-15-table').style.display = 'none'
document.querySelector('.shippuuden-season-17-table').style.display = 'none'
document.querySelector('.shippuuden-season-18-table').style.display = 'none'
document.querySelector('.shippuuden-season-19-table').style.display = 'none'
document.querySelector('.shippuuden-season-20-table').style.display = 'none'
document.querySelector('.shippuuden-season-21-table').style.display = 'none'
document.querySelector('.shippuuden-movies-table').style.display = 'none'
break;
case 'ss17':
lastSelectedButton = this.name
document.querySelector('.shippuuden-season-17-table').style.display = 'flex'
document.querySelector('.shippuuden-season-1-table').style.display = 'none'
document.querySelector('.shippuuden-season-2-table').style.display = 'none'
document.querySelector('.shippuuden-season-3-table').style.display = 'none'
document.querySelector('.shippuuden-season-4-table').style.display = 'none'
document.querySelector('.shippuuden-season-5-table').style.display = 'none'
document.querySelector('.shippuuden-season-6-table').style.display = 'none'
document.querySelector('.shippuuden-season-7-table').style.display = 'none'
document.querySelector('.shippuuden-season-8-table').style.display = 'none'
document.querySelector('.shippuuden-season-9-table').style.display = 'none'
document.querySelector('.shippuuden-season-10-table').style.display = 'none'
document.querySelector('.shippuuden-season-11-table').style.display = 'none'
document.querySelector('.shippuuden-season-12-table').style.display = 'none'
document.querySelector('.shippuuden-season-13-table').style.display = 'none'
document.querySelector('.shippuuden-season-14-table').style.display = 'none'
document.querySelector('.shippuuden-season-15-table').style.display = 'none'
document.querySelector('.shippuuden-season-16-table').style.display = 'none'
document.querySelector('.shippuuden-season-18-table').style.display = 'none'
document.querySelector('.shippuuden-season-19-table').style.display = 'none'
document.querySelector('.shippuuden-season-20-table').style.display = 'none'
document.querySelector('.shippuuden-season-21-table').style.display = 'none'
document.querySelector('.shippuuden-movies-table').style.display = 'none'
break;
case 'ss18':
lastSelectedButton = this.name
document.querySelector('.shippuuden-season-18-table').style.display = 'flex'
document.querySelector('.shippuuden-season-1-table').style.display = 'none'
document.querySelector('.shippuuden-season-2-table').style.display = 'none'
document.querySelector('.shippuuden-season-3-table').style.display = 'none'
document.querySelector('.shippuuden-season-4-table').style.display = 'none'
document.querySelector('.shippuuden-season-5-table').style.display = 'none'
document.querySelector('.shippuuden-season-6-table').style.display = 'none'
document.querySelector('.shippuuden-season-7-table').style.display = 'none'
document.querySelector('.shippuuden-season-8-table').style.display = 'none'
document.querySelector('.shippuuden-season-9-table').style.display = 'none'
document.querySelector('.shippuuden-season-10-table').style.display = 'none'
document.querySelector('.shippuuden-season-11-table').style.display = 'none'
document.querySelector('.shippuuden-season-12-table').style.display = 'none'
document.querySelector('.shippuuden-season-13-table').style.display = 'none'
document.querySelector('.shippuuden-season-14-table').style.display = 'none'
document.querySelector('.shippuuden-season-15-table').style.display = 'none'
document.querySelector('.shippuuden-season-16-table').style.display = 'none'
document.querySelector('.shippuuden-season-17-table').style.display = 'none'
document.querySelector('.shippuuden-season-19-table').style.display = 'none'
document.querySelector('.shippuuden-season-20-table').style.display = 'none'
document.querySelector('.shippuuden-season-21-table').style.display = 'none'
document.querySelector('.shippuuden-movies-table').style.display = 'none'
break;
case 'ss19':
lastSelectedButton = this.name
document.querySelector('.shippuuden-season-19-table').style.display = 'flex'
document.querySelector('.shippuuden-season-1-table').style.display = 'none'
document.querySelector('.shippuuden-season-2-table').style.display = 'none'
document.querySelector('.shippuuden-season-3-table').style.display = 'none'
document.querySelector('.shippuuden-season-4-table').style.display = 'none'
document.querySelector('.shippuuden-season-5-table').style.display = 'none'
document.querySelector('.shippuuden-season-6-table').style.display = 'none'
document.querySelector('.shippuuden-season-7-table').style.display = 'none'
document.querySelector('.shippuuden-season-8-table').style.display = 'none'
document.querySelector('.shippuuden-season-9-table').style.display = 'none'
document.querySelector('.shippuuden-season-10-table').style.display = 'none'
document.querySelector('.shippuuden-season-11-table').style.display = 'none'
document.querySelector('.shippuuden-season-12-table').style.display = 'none'
document.querySelector('.shippuuden-season-13-table').style.display = 'none'
document.querySelector('.shippuuden-season-14-table').style.display = 'none'
document.querySelector('.shippuuden-season-15-table').style.display = 'none'
document.querySelector('.shippuuden-season-16-table').style.display = 'none'
document.querySelector('.shippuuden-season-17-table').style.display = 'none'
document.querySelector('.shippuuden-season-18-table').style.display = 'none'
document.querySelector('.shippuuden-season-20-table').style.display = 'none'
document.querySelector('.shippuuden-season-21-table').style.display = 'none'
document.querySelector('.shippuuden-movies-table').style.display = 'none'
break;
case 'ss20':
lastSelectedButton = this.name
document.querySelector('.shippuuden-season-20-table').style.display = 'flex'
document.querySelector('.shippuuden-season-1-table').style.display = 'none'
document.querySelector('.shippuuden-season-2-table').style.display = 'none'
document.querySelector('.shippuuden-season-3-table').style.display = 'none'
document.querySelector('.shippuuden-season-4-table').style.display = 'none'
document.querySelector('.shippuuden-season-5-table').style.display = 'none'
document.querySelector('.shippuuden-season-6-table').style.display = 'none'
document.querySelector('.shippuuden-season-7-table').style.display = 'none'
document.querySelector('.shippuuden-season-8-table').style.display = 'none'
document.querySelector('.shippuuden-season-9-table').style.display = 'none'
document.querySelector('.shippuuden-season-10-table').style.display = 'none'
document.querySelector('.shippuuden-season-11-table').style.display = 'none'
document.querySelector('.shippuuden-season-12-table').style.display = 'none'
document.querySelector('.shippuuden-season-13-table').style.display = 'none'
document.querySelector('.shippuuden-season-14-table').style.display = 'none'
document.querySelector('.shippuuden-season-15-table').style.display = 'none'
document.querySelector('.shippuuden-season-16-table').style.display = 'none'
document.querySelector('.shippuuden-season-17-table').style.display = 'none'
document.querySelector('.shippuuden-season-18-table').style.display = 'none'
document.querySelector('.shippuuden-season-19-table').style.display = 'none'
document.querySelector('.shippuuden-season-21-table').style.display = 'none'
document.querySelector('.shippuuden-movies-table').style.display = 'none'
break;
case 'ss21':
lastSelectedButton = this.name
document.querySelector('.shippuuden-season-21-table').style.display = 'flex'
document.querySelector('.shippuuden-season-1-table').style.display = 'none'
document.querySelector('.shippuuden-season-2-table').style.display = 'none'
document.querySelector('.shippuuden-season-3-table').style.display = 'none'
document.querySelector('.shippuuden-season-4-table').style.display = 'none'
document.querySelector('.shippuuden-season-5-table').style.display = 'none'
document.querySelector('.shippuuden-season-6-table').style.display = 'none'
document.querySelector('.shippuuden-season-7-table').style.display = 'none'
document.querySelector('.shippuuden-season-8-table').style.display = 'none'
document.querySelector('.shippuuden-season-9-table').style.display = 'none'
document.querySelector('.shippuuden-season-10-table').style.display = 'none'
document.querySelector('.shippuuden-season-11-table').style.display = 'none'
document.querySelector('.shippuuden-season-12-table').style.display = 'none'
document.querySelector('.shippuuden-season-13-table').style.display = 'none'
document.querySelector('.shippuuden-season-14-table').style.display = 'none'
document.querySelector('.shippuuden-season-15-table').style.display = 'none'
document.querySelector('.shippuuden-season-16-table').style.display = 'none'
document.querySelector('.shippuuden-season-17-table').style.display = 'none'
document.querySelector('.shippuuden-season-18-table').style.display = 'none'
document.querySelector('.shippuuden-season-19-table').style.display = 'none'
document.querySelector('.shippuuden-season-20-table').style.display = 'none'
document.querySelector('.shippuuden-movies-table').style.display = 'none'
break;
case 'ssm':
lastSelectedButton = this.name
document.querySelector('.shippuuden-movies-table').style.display = 'flex'
document.querySelector('.shippuuden-season-1-table').style.display = 'none'
document.querySelector('.shippuuden-season-2-table').style.display = 'none'
document.querySelector('.shippuuden-season-3-table').style.display = 'none'
document.querySelector('.shippuuden-season-4-table').style.display = 'none'
document.querySelector('.shippuuden-season-5-table').style.display = 'none'
document.querySelector('.shippuuden-season-6-table').style.display = 'none'
document.querySelector('.shippuuden-season-7-table').style.display = 'none'
document.querySelector('.shippuuden-season-8-table').style.display = 'none'
document.querySelector('.shippuuden-season-9-table').style.display = 'none'
document.querySelector('.shippuuden-season-10-table').style.display = 'none'
document.querySelector('.shippuuden-season-11-table').style.display = 'none'
document.querySelector('.shippuuden-season-12-table').style.display = 'none'
document.querySelector('.shippuuden-season-13-table').style.display = 'none'
document.querySelector('.shippuuden-season-14-table').style.display = 'none'
document.querySelector('.shippuuden-season-15-table').style.display = 'none'
document.querySelector('.shippuuden-season-16-table').style.display = 'none'
document.querySelector('.shippuuden-season-17-table').style.display = 'none'
document.querySelector('.shippuuden-season-18-table').style.display = 'none'
document.querySelector('.shippuuden-season-19-table').style.display = 'none'
document.querySelector('.shippuuden-season-20-table').style.display = 'none'
document.querySelector('.shippuuden-season-21-table').style.display = 'none'
break;
*/
