const buttons = document.querySelectorAll('button[name]')
buttons.forEach(button => button.addEventListener('click', showItem))

function showItem(event) {
  console.log(event)
  console.log(event.srcElement.name)
  switch(event.srcElement.name) {
    case 'naruto':
    document.querySelector('#naruto-episode-selection').style.display = 'block'
    document.querySelector('#shippuuden-episode-selection').style.display = 'none'
    document.querySelector('.shippuuden-season-1-table').style.display = 'none'
    document.querySelector('.shippuuden-season-2-table').style.display = 'none'
    document.querySelector('.shippuuden-season-3-table').style.display = 'none'
    document.querySelector('.shippuuden-season-4-table').style.display = 'none'
    document.querySelector('.shippuuden-season-5-table').style.display = 'none'
    document.querySelector('.shippuuden-season-6-table').style.display = 'none'
    document.querySelector('.shippuuden-season-7-table').style.display = 'none'
    document.querySelector('.shippuuden-season-8-table').style.display = 'none'
    document.querySelector('.shippuuden-season-9-table').style.display = 'none'
    document.querySelector('.shippuuden-season-10-table').style.display = 'none'
    document.querySelector('.shippuuden-season-11-table').style.display = 'none'
    document.querySelector('.shippuuden-season-12-table').style.display = 'none'
    document.querySelector('.shippuuden-season-13-table').style.display = 'none'
    document.querySelector('.shippuuden-season-14-table').style.display = 'none'
    document.querySelector('.shippuuden-season-15-table').style.display = 'none'
    document.querySelector('.shippuuden-season-16-table').style.display = 'none'
    document.querySelector('.shippuuden-season-17-table').style.display = 'none'
    document.querySelector('.shippuuden-season-18-table').style.display = 'none'
    document.querySelector('.shippuuden-season-19-table').style.display = 'none'
    document.querySelector('.shippuuden-season-20-table').style.display = 'none'
    document.querySelector('.shippuuden-season-21-table').style.display = 'none'
    document.querySelector('.shippuuden-movies-table').style.display = 'none'
    break;
    case 'shippuuden':
    document.querySelector('#shippuuden-episode-selection').style.display = 'block'
    document.querySelector('#naruto-episode-selection').style.display = 'none'
    document.querySelector('.naruto-movies-table').style.display = 'none'
    document.querySelector('.naruto-season-1-table').style.display = 'none'
    document.querySelector('.naruto-season-2-table').style.display = 'none'
    document.querySelector('.naruto-season-3-table').style.display = 'none'
    document.querySelector('.naruto-season-4-table').style.display = 'none'
    document.querySelector('.naruto-season-5-table').style.display = 'none'
    document.querySelector('.naruto-season-6-table').style.display = 'none'
    document.querySelector('.naruto-season-7-table').style.display = 'none'
    document.querySelector('.naruto-season-8-table').style.display = 'none'
    document.querySelector('.naruto-season-9-table').style.display = 'none'
    break;
    case 'ns1':
    document.querySelector('.naruto-season-1-table').style.display = 'flex'
    document.querySelector('.naruto-season-2-table').style.display = 'none'
    document.querySelector('.naruto-season-3-table').style.display = 'none'
    document.querySelector('.naruto-season-4-table').style.display = 'none'
    document.querySelector('.naruto-season-5-table').style.display = 'none'
    document.querySelector('.naruto-season-6-table').style.display = 'none'
    document.querySelector('.naruto-season-7-table').style.display = 'none'
    document.querySelector('.naruto-season-8-table').style.display = 'none'
    document.querySelector('.naruto-season-9-table').style.display = 'none'
    document.querySelector('.naruto-movies-table').style.display = 'none'
    break;
    case 'ns2':
    document.querySelector('.naruto-season-2-table').style.display = 'flex'
    document.querySelector('.naruto-season-1-table').style.display = 'none'
    document.querySelector('.naruto-season-3-table').style.display = 'none'
    document.querySelector('.naruto-season-4-table').style.display = 'none'
    document.querySelector('.naruto-season-5-table').style.display = 'none'
    document.querySelector('.naruto-season-6-table').style.display = 'none'
    document.querySelector('.naruto-season-7-table').style.display = 'none'
    document.querySelector('.naruto-season-8-table').style.display = 'none'
    document.querySelector('.naruto-season-9-table').style.display = 'none'
    document.querySelector('.naruto-movies-table').style.display = 'none'
    break;
    case 'ns3':
    document.querySelector('.naruto-season-3-table').style.display = 'flex'
    document.querySelector('.naruto-season-1-table').style.display = 'none'
    document.querySelector('.naruto-season-2-table').style.display = 'none'
    document.querySelector('.naruto-season-4-table').style.display = 'none'
    document.querySelector('.naruto-season-5-table').style.display = 'none'
    document.querySelector('.naruto-season-6-table').style.display = 'none'
    document.querySelector('.naruto-season-7-table').style.display = 'none'
    document.querySelector('.naruto-season-8-table').style.display = 'none'
    document.querySelector('.naruto-season-9-table').style.display = 'none'
    document.querySelector('.naruto-movies-table').style.display = 'none'
    break;
    case 'ns4':
    document.querySelector('.naruto-season-4-table').style.display = 'flex'
    document.querySelector('.naruto-season-1-table').style.display = 'none'
    document.querySelector('.naruto-season-2-table').style.display = 'none'
    document.querySelector('.naruto-season-3-table').style.display = 'none'
    document.querySelector('.naruto-season-5-table').style.display = 'none'
    document.querySelector('.naruto-season-6-table').style.display = 'none'
    document.querySelector('.naruto-season-7-table').style.display = 'none'
    document.querySelector('.naruto-season-8-table').style.display = 'none'
    document.querySelector('.naruto-season-9-table').style.display = 'none'
    document.querySelector('.naruto-movies-table').style.display = 'none'
    break;
    case 'ns5':
    document.querySelector('.naruto-season-5-table').style.display = 'flex'
    document.querySelector('.naruto-season-1-table').style.display = 'none'
    document.querySelector('.naruto-season-2-table').style.display = 'none'
    document.querySelector('.naruto-season-3-table').style.display = 'none'
    document.querySelector('.naruto-season-4-table').style.display = 'none'
    document.querySelector('.naruto-season-6-table').style.display = 'none'
    document.querySelector('.naruto-season-7-table').style.display = 'none'
    document.querySelector('.naruto-season-8-table').style.display = 'none'
    document.querySelector('.naruto-season-9-table').style.display = 'none'
    document.querySelector('.naruto-movies-table').style.display = 'none'
    break;
    case 'ns6':
    document.querySelector('.naruto-season-6-table').style.display = 'flex'
    document.querySelector('.naruto-season-1-table').style.display = 'none'
    document.querySelector('.naruto-season-2-table').style.display = 'none'
    document.querySelector('.naruto-season-3-table').style.display = 'none'
    document.querySelector('.naruto-season-4-table').style.display = 'none'
    document.querySelector('.naruto-season-5-table').style.display = 'none'
    document.querySelector('.naruto-season-7-table').style.display = 'none'
    document.querySelector('.naruto-season-8-table').style.display = 'none'
    document.querySelector('.naruto-season-9-table').style.display = 'none'
    document.querySelector('.naruto-movies-table').style.display = 'none'
    break;
    case 'ns7':
    document.querySelector('.naruto-season-7-table').style.display = 'flex'
    document.querySelector('.naruto-season-1-table').style.display = 'none'
    document.querySelector('.naruto-season-2-table').style.display = 'none'
    document.querySelector('.naruto-season-3-table').style.display = 'none'
    document.querySelector('.naruto-season-4-table').style.display = 'none'
    document.querySelector('.naruto-season-5-table').style.display = 'none'
    document.querySelector('.naruto-season-6-table').style.display = 'none'
    document.querySelector('.naruto-season-8-table').style.display = 'none'
    document.querySelector('.naruto-season-9-table').style.display = 'none'
    document.querySelector('.naruto-movies-table').style.display = 'none'
    break;
    case 'ns8':
    document.querySelector('.naruto-season-8-table').style.display = 'flex'
    document.querySelector('.naruto-season-1-table').style.display = 'none'
    document.querySelector('.naruto-season-2-table').style.display = 'none'
    document.querySelector('.naruto-season-3-table').style.display = 'none'
    document.querySelector('.naruto-season-4-table').style.display = 'none'
    document.querySelector('.naruto-season-5-table').style.display = 'none'
    document.querySelector('.naruto-season-6-table').style.display = 'none'
    document.querySelector('.naruto-season-7-table').style.display = 'none'
    document.querySelector('.naruto-season-9-table').style.display = 'none'
    document.querySelector('.naruto-movies-table').style.display = 'none'
    break;
    case 'ns9':
    document.querySelector('.naruto-season-9-table').style.display = 'flex'
    document.querySelector('.naruto-season-1-table').style.display = 'none'
    document.querySelector('.naruto-season-2-table').style.display = 'none'
    document.querySelector('.naruto-season-3-table').style.display = 'none'
    document.querySelector('.naruto-season-4-table').style.display = 'none'
    document.querySelector('.naruto-season-5-table').style.display = 'none'
    document.querySelector('.naruto-season-6-table').style.display = 'none'
    document.querySelector('.naruto-season-7-table').style.display = 'none'
    document.querySelector('.naruto-season-8-table').style.display = 'none'
    document.querySelector('.naruto-movies-table').style.display = 'none'
    break;
    case 'nsm':
    document.querySelector('.naruto-movies-table').style.display = 'flex'
    document.querySelector('.naruto-season-1-table').style.display = 'none'
    document.querySelector('.naruto-season-2-table').style.display = 'none'
    document.querySelector('.naruto-season-3-table').style.display = 'none'
    document.querySelector('.naruto-season-4-table').style.display = 'none'
    document.querySelector('.naruto-season-5-table').style.display = 'none'
    document.querySelector('.naruto-season-6-table').style.display = 'none'
    document.querySelector('.naruto-season-7-table').style.display = 'none'
    document.querySelector('.naruto-season-8-table').style.display = 'none'
    document.querySelector('.naruto-season-9-table').style.display = 'none'
    break;
    case 'ss1':
    document.querySelector('.shippuuden-season-1-table').style.display = 'flex'
    document.querySelector('.shippuuden-season-2-table').style.display = 'none'
    document.querySelector('.shippuuden-season-3-table').style.display = 'none'
    document.querySelector('.shippuuden-season-4-table').style.display = 'none'
    document.querySelector('.shippuuden-season-5-table').style.display = 'none'
    document.querySelector('.shippuuden-season-6-table').style.display = 'none'
    document.querySelector('.shippuuden-season-7-table').style.display = 'none'
    document.querySelector('.shippuuden-season-8-table').style.display = 'none'
    document.querySelector('.shippuuden-season-9-table').style.display = 'none'
    document.querySelector('.shippuuden-season-10-table').style.display = 'none'
    document.querySelector('.shippuuden-season-11-table').style.display = 'none'
    document.querySelector('.shippuuden-season-12-table').style.display = 'none'
    document.querySelector('.shippuuden-season-13-table').style.display = 'none'
    document.querySelector('.shippuuden-season-14-table').style.display = 'none'
    document.querySelector('.shippuuden-season-15-table').style.display = 'none'
    document.querySelector('.shippuuden-season-16-table').style.display = 'none'
    document.querySelector('.shippuuden-season-17-table').style.display = 'none'
    document.querySelector('.shippuuden-season-18-table').style.display = 'none'
    document.querySelector('.shippuuden-season-19-table').style.display = 'none'
    document.querySelector('.shippuuden-season-20-table').style.display = 'none'
    document.querySelector('.shippuuden-season-21-table').style.display = 'none'
    document.querySelector('.shippuuden-movies-table').style.display = 'none'
    break;
    case 'ss2':
    document.querySelector('.shippuuden-season-2-table').style.display = 'flex'
    document.querySelector('.shippuuden-season-1-table').style.display = 'none'
    document.querySelector('.shippuuden-season-3-table').style.display = 'none'
    document.querySelector('.shippuuden-season-4-table').style.display = 'none'
    document.querySelector('.shippuuden-season-5-table').style.display = 'none'
    document.querySelector('.shippuuden-season-6-table').style.display = 'none'
    document.querySelector('.shippuuden-season-7-table').style.display = 'none'
    document.querySelector('.shippuuden-season-8-table').style.display = 'none'
    document.querySelector('.shippuuden-season-9-table').style.display = 'none'
    document.querySelector('.shippuuden-season-10-table').style.display = 'none'
    document.querySelector('.shippuuden-season-11-table').style.display = 'none'
    document.querySelector('.shippuuden-season-12-table').style.display = 'none'
    document.querySelector('.shippuuden-season-13-table').style.display = 'none'
    document.querySelector('.shippuuden-season-14-table').style.display = 'none'
    document.querySelector('.shippuuden-season-15-table').style.display = 'none'
    document.querySelector('.shippuuden-season-16-table').style.display = 'none'
    document.querySelector('.shippuuden-season-17-table').style.display = 'none'
    document.querySelector('.shippuuden-season-18-table').style.display = 'none'
    document.querySelector('.shippuuden-season-19-table').style.display = 'none'
    document.querySelector('.shippuuden-season-20-table').style.display = 'none'
    document.querySelector('.shippuuden-season-21-table').style.display = 'none'
    document.querySelector('.shippuuden-movies-table').style.display = 'none'
    break;
    case 'ss3':
    document.querySelector('.shippuuden-season-3-table').style.display = 'flex'
    document.querySelector('.shippuuden-season-1-table').style.display = 'none'
    document.querySelector('.shippuuden-season-2-table').style.display = 'none'
    document.querySelector('.shippuuden-season-4-table').style.display = 'none'
    document.querySelector('.shippuuden-season-5-table').style.display = 'none'
    document.querySelector('.shippuuden-season-6-table').style.display = 'none'
    document.querySelector('.shippuuden-season-7-table').style.display = 'none'
    document.querySelector('.shippuuden-season-8-table').style.display = 'none'
    document.querySelector('.shippuuden-season-9-table').style.display = 'none'
    document.querySelector('.shippuuden-season-10-table').style.display = 'none'
    document.querySelector('.shippuuden-season-11-table').style.display = 'none'
    document.querySelector('.shippuuden-season-12-table').style.display = 'none'
    document.querySelector('.shippuuden-season-13-table').style.display = 'none'
    document.querySelector('.shippuuden-season-14-table').style.display = 'none'
    document.querySelector('.shippuuden-season-15-table').style.display = 'none'
    document.querySelector('.shippuuden-season-16-table').style.display = 'none'
    document.querySelector('.shippuuden-season-17-table').style.display = 'none'
    document.querySelector('.shippuuden-season-18-table').style.display = 'none'
    document.querySelector('.shippuuden-season-19-table').style.display = 'none'
    document.querySelector('.shippuuden-season-20-table').style.display = 'none'
    document.querySelector('.shippuuden-season-21-table').style.display = 'none'
    document.querySelector('.shippuuden-movies-table').style.display = 'none'
    break;
    case 'ss4':
    document.querySelector('.shippuuden-season-4-table').style.display = 'flex'
    document.querySelector('.shippuuden-season-1-table').style.display = 'none'
    document.querySelector('.shippuuden-season-2-table').style.display = 'none'
    document.querySelector('.shippuuden-season-3-table').style.display = 'none'
    document.querySelector('.shippuuden-season-5-table').style.display = 'none'
    document.querySelector('.shippuuden-season-6-table').style.display = 'none'
    document.querySelector('.shippuuden-season-7-table').style.display = 'none'
    document.querySelector('.shippuuden-season-8-table').style.display = 'none'
    document.querySelector('.shippuuden-season-9-table').style.display = 'none'
    document.querySelector('.shippuuden-season-10-table').style.display = 'none'
    document.querySelector('.shippuuden-season-11-table').style.display = 'none'
    document.querySelector('.shippuuden-season-12-table').style.display = 'none'
    document.querySelector('.shippuuden-season-13-table').style.display = 'none'
    document.querySelector('.shippuuden-season-14-table').style.display = 'none'
    document.querySelector('.shippuuden-season-15-table').style.display = 'none'
    document.querySelector('.shippuuden-season-16-table').style.display = 'none'
    document.querySelector('.shippuuden-season-17-table').style.display = 'none'
    document.querySelector('.shippuuden-season-18-table').style.display = 'none'
    document.querySelector('.shippuuden-season-19-table').style.display = 'none'
    document.querySelector('.shippuuden-season-20-table').style.display = 'none'
    document.querySelector('.shippuuden-season-21-table').style.display = 'none'
    document.querySelector('.shippuuden-movies-table').style.display = 'none'
    break;
    case 'ss5':
    document.querySelector('.shippuuden-season-5-table').style.display = 'flex'
    document.querySelector('.shippuuden-season-1-table').style.display = 'none'
    document.querySelector('.shippuuden-season-2-table').style.display = 'none'
    document.querySelector('.shippuuden-season-3-table').style.display = 'none'
    document.querySelector('.shippuuden-season-4-table').style.display = 'none'
    document.querySelector('.shippuuden-season-6-table').style.display = 'none'
    document.querySelector('.shippuuden-season-7-table').style.display = 'none'
    document.querySelector('.shippuuden-season-8-table').style.display = 'none'
    document.querySelector('.shippuuden-season-9-table').style.display = 'none'
    document.querySelector('.shippuuden-season-10-table').style.display = 'none'
    document.querySelector('.shippuuden-season-11-table').style.display = 'none'
    document.querySelector('.shippuuden-season-12-table').style.display = 'none'
    document.querySelector('.shippuuden-season-13-table').style.display = 'none'
    document.querySelector('.shippuuden-season-14-table').style.display = 'none'
    document.querySelector('.shippuuden-season-15-table').style.display = 'none'
    document.querySelector('.shippuuden-season-16-table').style.display = 'none'
    document.querySelector('.shippuuden-season-17-table').style.display = 'none'
    document.querySelector('.shippuuden-season-18-table').style.display = 'none'
    document.querySelector('.shippuuden-season-19-table').style.display = 'none'
    document.querySelector('.shippuuden-season-20-table').style.display = 'none'
    document.querySelector('.shippuuden-season-21-table').style.display = 'none'
    document.querySelector('.shippuuden-movies-table').style.display = 'none'
    break;
    case 'ss6':
    document.querySelector('.shippuuden-season-6-table').style.display = 'flex'
    document.querySelector('.shippuuden-season-1-table').style.display = 'none'
    document.querySelector('.shippuuden-season-2-table').style.display = 'none'
    document.querySelector('.shippuuden-season-3-table').style.display = 'none'
    document.querySelector('.shippuuden-season-4-table').style.display = 'none'
    document.querySelector('.shippuuden-season-5-table').style.display = 'none'
    document.querySelector('.shippuuden-season-7-table').style.display = 'none'
    document.querySelector('.shippuuden-season-8-table').style.display = 'none'
    document.querySelector('.shippuuden-season-9-table').style.display = 'none'
    document.querySelector('.shippuuden-season-10-table').style.display = 'none'
    document.querySelector('.shippuuden-season-11-table').style.display = 'none'
    document.querySelector('.shippuuden-season-12-table').style.display = 'none'
    document.querySelector('.shippuuden-season-13-table').style.display = 'none'
    document.querySelector('.shippuuden-season-14-table').style.display = 'none'
    document.querySelector('.shippuuden-season-15-table').style.display = 'none'
    document.querySelector('.shippuuden-season-16-table').style.display = 'none'
    document.querySelector('.shippuuden-season-17-table').style.display = 'none'
    document.querySelector('.shippuuden-season-18-table').style.display = 'none'
    document.querySelector('.shippuuden-season-19-table').style.display = 'none'
    document.querySelector('.shippuuden-season-20-table').style.display = 'none'
    document.querySelector('.shippuuden-season-21-table').style.display = 'none'
    document.querySelector('.shippuuden-movies-table').style.display = 'none'
    break;
    case 'ss7':
    document.querySelector('.shippuuden-season-7-table').style.display = 'flex'
    document.querySelector('.shippuuden-season-1-table').style.display = 'none'
    document.querySelector('.shippuuden-season-2-table').style.display = 'none'
    document.querySelector('.shippuuden-season-3-table').style.display = 'none'
    document.querySelector('.shippuuden-season-4-table').style.display = 'none'
    document.querySelector('.shippuuden-season-5-table').style.display = 'none'
    document.querySelector('.shippuuden-season-6-table').style.display = 'none'
    document.querySelector('.shippuuden-season-8-table').style.display = 'none'
    document.querySelector('.shippuuden-season-9-table').style.display = 'none'
    document.querySelector('.shippuuden-season-10-table').style.display = 'none'
    document.querySelector('.shippuuden-season-11-table').style.display = 'none'
    document.querySelector('.shippuuden-season-12-table').style.display = 'none'
    document.querySelector('.shippuuden-season-13-table').style.display = 'none'
    document.querySelector('.shippuuden-season-14-table').style.display = 'none'
    document.querySelector('.shippuuden-season-15-table').style.display = 'none'
    document.querySelector('.shippuuden-season-16-table').style.display = 'none'
    document.querySelector('.shippuuden-season-17-table').style.display = 'none'
    document.querySelector('.shippuuden-season-18-table').style.display = 'none'
    document.querySelector('.shippuuden-season-19-table').style.display = 'none'
    document.querySelector('.shippuuden-season-20-table').style.display = 'none'
    document.querySelector('.shippuuden-season-21-table').style.display = 'none'
    document.querySelector('.shippuuden-movies-table').style.display = 'none'
    break;
    case 'ss8':
    document.querySelector('.shippuuden-season-8-table').style.display = 'flex'
    document.querySelector('.shippuuden-season-1-table').style.display = 'none'
    document.querySelector('.shippuuden-season-2-table').style.display = 'none'
    document.querySelector('.shippuuden-season-3-table').style.display = 'none'
    document.querySelector('.shippuuden-season-4-table').style.display = 'none'
    document.querySelector('.shippuuden-season-5-table').style.display = 'none'
    document.querySelector('.shippuuden-season-6-table').style.display = 'none'
    document.querySelector('.shippuuden-season-7-table').style.display = 'none'
    document.querySelector('.shippuuden-season-9-table').style.display = 'none'
    document.querySelector('.shippuuden-season-10-table').style.display = 'none'
    document.querySelector('.shippuuden-season-11-table').style.display = 'none'
    document.querySelector('.shippuuden-season-12-table').style.display = 'none'
    document.querySelector('.shippuuden-season-13-table').style.display = 'none'
    document.querySelector('.shippuuden-season-14-table').style.display = 'none'
    document.querySelector('.shippuuden-season-15-table').style.display = 'none'
    document.querySelector('.shippuuden-season-16-table').style.display = 'none'
    document.querySelector('.shippuuden-season-17-table').style.display = 'none'
    document.querySelector('.shippuuden-season-18-table').style.display = 'none'
    document.querySelector('.shippuuden-season-19-table').style.display = 'none'
    document.querySelector('.shippuuden-season-20-table').style.display = 'none'
    document.querySelector('.shippuuden-season-21-table').style.display = 'none'
    document.querySelector('.shippuuden-movies-table').style.display = 'none'
    break;
    case 'ss9':
    document.querySelector('.shippuuden-season-9-table').style.display = 'flex'
    document.querySelector('.shippuuden-season-1-table').style.display = 'none'
    document.querySelector('.shippuuden-season-2-table').style.display = 'none'
    document.querySelector('.shippuuden-season-3-table').style.display = 'none'
    document.querySelector('.shippuuden-season-4-table').style.display = 'none'
    document.querySelector('.shippuuden-season-5-table').style.display = 'none'
    document.querySelector('.shippuuden-season-6-table').style.display = 'none'
    document.querySelector('.shippuuden-season-7-table').style.display = 'none'
    document.querySelector('.shippuuden-season-8-table').style.display = 'none'
    document.querySelector('.shippuuden-season-10-table').style.display = 'none'
    document.querySelector('.shippuuden-season-11-table').style.display = 'none'
    document.querySelector('.shippuuden-season-12-table').style.display = 'none'
    document.querySelector('.shippuuden-season-13-table').style.display = 'none'
    document.querySelector('.shippuuden-season-14-table').style.display = 'none'
    document.querySelector('.shippuuden-season-15-table').style.display = 'none'
    document.querySelector('.shippuuden-season-16-table').style.display = 'none'
    document.querySelector('.shippuuden-season-17-table').style.display = 'none'
    document.querySelector('.shippuuden-season-18-table').style.display = 'none'
    document.querySelector('.shippuuden-season-19-table').style.display = 'none'
    document.querySelector('.shippuuden-season-20-table').style.display = 'none'
    document.querySelector('.shippuuden-season-21-table').style.display = 'none'
    document.querySelector('.shippuuden-movies-table').style.display = 'none'
    break;
    case 'ss10':
    document.querySelector('.shippuuden-season-10-table').style.display = 'flex'
    document.querySelector('.shippuuden-season-1-table').style.display = 'none'
    document.querySelector('.shippuuden-season-2-table').style.display = 'none'
    document.querySelector('.shippuuden-season-3-table').style.display = 'none'
    document.querySelector('.shippuuden-season-4-table').style.display = 'none'
    document.querySelector('.shippuuden-season-5-table').style.display = 'none'
    document.querySelector('.shippuuden-season-6-table').style.display = 'none'
    document.querySelector('.shippuuden-season-7-table').style.display = 'none'
    document.querySelector('.shippuuden-season-8-table').style.display = 'none'
    document.querySelector('.shippuuden-season-9-table').style.display = 'none'
    document.querySelector('.shippuuden-season-11-table').style.display = 'none'
    document.querySelector('.shippuuden-season-12-table').style.display = 'none'
    document.querySelector('.shippuuden-season-13-table').style.display = 'none'
    document.querySelector('.shippuuden-season-14-table').style.display = 'none'
    document.querySelector('.shippuuden-season-15-table').style.display = 'none'
    document.querySelector('.shippuuden-season-16-table').style.display = 'none'
    document.querySelector('.shippuuden-season-17-table').style.display = 'none'
    document.querySelector('.shippuuden-season-18-table').style.display = 'none'
    document.querySelector('.shippuuden-season-19-table').style.display = 'none'
    document.querySelector('.shippuuden-season-20-table').style.display = 'none'
    document.querySelector('.shippuuden-season-21-table').style.display = 'none'
    document.querySelector('.shippuuden-movies-table').style.display = 'none'
    break;
    case 'ss11':
    document.querySelector('.shippuuden-season-11-table').style.display = 'flex'
    document.querySelector('.shippuuden-season-1-table').style.display = 'none'
    document.querySelector('.shippuuden-season-2-table').style.display = 'none'
    document.querySelector('.shippuuden-season-3-table').style.display = 'none'
    document.querySelector('.shippuuden-season-4-table').style.display = 'none'
    document.querySelector('.shippuuden-season-5-table').style.display = 'none'
    document.querySelector('.shippuuden-season-6-table').style.display = 'none'
    document.querySelector('.shippuuden-season-7-table').style.display = 'none'
    document.querySelector('.shippuuden-season-8-table').style.display = 'none'
    document.querySelector('.shippuuden-season-9-table').style.display = 'none'
    document.querySelector('.shippuuden-season-10-table').style.display = 'none'
    document.querySelector('.shippuuden-season-12-table').style.display = 'none'
    document.querySelector('.shippuuden-season-13-table').style.display = 'none'
    document.querySelector('.shippuuden-season-14-table').style.display = 'none'
    document.querySelector('.shippuuden-season-15-table').style.display = 'none'
    document.querySelector('.shippuuden-season-16-table').style.display = 'none'
    document.querySelector('.shippuuden-season-17-table').style.display = 'none'
    document.querySelector('.shippuuden-season-18-table').style.display = 'none'
    document.querySelector('.shippuuden-season-19-table').style.display = 'none'
    document.querySelector('.shippuuden-season-20-table').style.display = 'none'
    document.querySelector('.shippuuden-season-21-table').style.display = 'none'
    document.querySelector('.shippuuden-movies-table').style.display = 'none'
    break;
    case 'ss12':
    document.querySelector('.shippuuden-season-12-table').style.display = 'flex'
    document.querySelector('.shippuuden-season-1-table').style.display = 'none'
    document.querySelector('.shippuuden-season-2-table').style.display = 'none'
    document.querySelector('.shippuuden-season-3-table').style.display = 'none'
    document.querySelector('.shippuuden-season-4-table').style.display = 'none'
    document.querySelector('.shippuuden-season-5-table').style.display = 'none'
    document.querySelector('.shippuuden-season-6-table').style.display = 'none'
    document.querySelector('.shippuuden-season-7-table').style.display = 'none'
    document.querySelector('.shippuuden-season-8-table').style.display = 'none'
    document.querySelector('.shippuuden-season-9-table').style.display = 'none'
    document.querySelector('.shippuuden-season-10-table').style.display = 'none'
    document.querySelector('.shippuuden-season-11-table').style.display = 'none'
    document.querySelector('.shippuuden-season-13-table').style.display = 'none'
    document.querySelector('.shippuuden-season-14-table').style.display = 'none'
    document.querySelector('.shippuuden-season-15-table').style.display = 'none'
    document.querySelector('.shippuuden-season-16-table').style.display = 'none'
    document.querySelector('.shippuuden-season-17-table').style.display = 'none'
    document.querySelector('.shippuuden-season-18-table').style.display = 'none'
    document.querySelector('.shippuuden-season-19-table').style.display = 'none'
    document.querySelector('.shippuuden-season-20-table').style.display = 'none'
    document.querySelector('.shippuuden-season-21-table').style.display = 'none'
    document.querySelector('.shippuuden-movies-table').style.display = 'none'
    break;
    case 'ss13':
    document.querySelector('.shippuuden-season-13-table').style.display = 'flex'
    document.querySelector('.shippuuden-season-1-table').style.display = 'none'
    document.querySelector('.shippuuden-season-2-table').style.display = 'none'
    document.querySelector('.shippuuden-season-3-table').style.display = 'none'
    document.querySelector('.shippuuden-season-4-table').style.display = 'none'
    document.querySelector('.shippuuden-season-5-table').style.display = 'none'
    document.querySelector('.shippuuden-season-6-table').style.display = 'none'
    document.querySelector('.shippuuden-season-7-table').style.display = 'none'
    document.querySelector('.shippuuden-season-8-table').style.display = 'none'
    document.querySelector('.shippuuden-season-9-table').style.display = 'none'
    document.querySelector('.shippuuden-season-10-table').style.display = 'none'
    document.querySelector('.shippuuden-season-11-table').style.display = 'none'
    document.querySelector('.shippuuden-season-12-table').style.display = 'none'
    document.querySelector('.shippuuden-season-14-table').style.display = 'none'
    document.querySelector('.shippuuden-season-15-table').style.display = 'none'
    document.querySelector('.shippuuden-season-16-table').style.display = 'none'
    document.querySelector('.shippuuden-season-17-table').style.display = 'none'
    document.querySelector('.shippuuden-season-18-table').style.display = 'none'
    document.querySelector('.shippuuden-season-19-table').style.display = 'none'
    document.querySelector('.shippuuden-season-20-table').style.display = 'none'
    document.querySelector('.shippuuden-season-21-table').style.display = 'none'
    document.querySelector('.shippuuden-movies-table').style.display = 'none'
    break;
    case 'ss14':
    document.querySelector('.shippuuden-season-14-table').style.display = 'flex'
    document.querySelector('.shippuuden-season-1-table').style.display = 'none'
    document.querySelector('.shippuuden-season-2-table').style.display = 'none'
    document.querySelector('.shippuuden-season-3-table').style.display = 'none'
    document.querySelector('.shippuuden-season-4-table').style.display = 'none'
    document.querySelector('.shippuuden-season-5-table').style.display = 'none'
    document.querySelector('.shippuuden-season-6-table').style.display = 'none'
    document.querySelector('.shippuuden-season-7-table').style.display = 'none'
    document.querySelector('.shippuuden-season-8-table').style.display = 'none'
    document.querySelector('.shippuuden-season-9-table').style.display = 'none'
    document.querySelector('.shippuuden-season-10-table').style.display = 'none'
    document.querySelector('.shippuuden-season-11.table').style.display = 'none'
    document.querySelector('.shippuuden-season-12-table').style.display = 'none'
    document.querySelector('.shippuuden-season-13-table').style.display = 'none'
    document.querySelector('.shippuuden-season-15-table').style.display = 'none'
    document.querySelector('.shippuuden-season-16-table').style.display = 'none'
    document.querySelector('.shippuuden-season-17-table').style.display = 'none'
    document.querySelector('.shippuuden-season-18-table').style.display = 'none'
    document.querySelector('.shippuuden-season-19-table').style.display = 'none'
    document.querySelector('.shippuuden-season-20-table').style.display = 'none'
    document.querySelector('.shippuuden-season-21-table').style.display = 'none'
    document.querySelector('.shippuuden-movies-table').style.display = 'none'
    break;
    case 'ss15':
    document.querySelector('.shippuuden-season-15-table').style.display = 'flex'
    document.querySelector('.shippuuden-season-1-table').style.display = 'none'
    document.querySelector('.shippuuden-season-2-table').style.display = 'none'
    document.querySelector('.shippuuden-season-3-table').style.display = 'none'
    document.querySelector('.shippuuden-season-4-table').style.display = 'none'
    document.querySelector('.shippuuden-season-5-table').style.display = 'none'
    document.querySelector('.shippuuden-season-6-table').style.display = 'none'
    document.querySelector('.shippuuden-season-7-table').style.display = 'none'
    document.querySelector('.shippuuden-season-8-table').style.display = 'none'
    document.querySelector('.shippuuden-season-9-table').style.display = 'none'
    document.querySelector('.shippuuden-season-10-table').style.display = 'none'
    document.querySelector('.shippuuden-season-11-table').style.display = 'none'
    document.querySelector('.shippuuden-season-12-table').style.display = 'none'
    document.querySelector('.shippuuden-season-13-table').style.display = 'none'
    document.querySelector('.shippuuden-season-14-table').style.display = 'none'
    document.querySelector('.shippuuden-season-16-table').style.display = 'none'
    document.querySelector('.shippuuden-season-17-table').style.display = 'none'
    document.querySelector('.shippuuden-season-18-table').style.display = 'none'
    document.querySelector('.shippuuden-season-19-table').style.display = 'none'
    document.querySelector('.shippuuden-season-20-table').style.display = 'none'
    document.querySelector('.shippuuden-season-21-table').style.display = 'none'
    document.querySelector('.shippuuden-movies-table').style.display = 'none'
    break;
    case 'ss16':
    document.querySelector('.shippuuden-season-16-table').style.display = 'flex'
    document.querySelector('.shippuuden-season-1-table').style.display = 'none'
    document.querySelector('.shippuuden-season-2-table').style.display = 'none'
    document.querySelector('.shippuuden-season-3-table').style.display = 'none'
    document.querySelector('.shippuuden-season-4-table').style.display = 'none'
    document.querySelector('.shippuuden-season-5-table').style.display = 'none'
    document.querySelector('.shippuuden-season-6-table').style.display = 'none'
    document.querySelector('.shippuuden-season-7-table').style.display = 'none'
    document.querySelector('.shippuuden-season-8-table').style.display = 'none'
    document.querySelector('.shippuuden-season-9-table').style.display = 'none'
    document.querySelector('.shippuuden-season-10-table').style.display = 'none'
    document.querySelector('.shippuuden-season-11-table').style.display = 'none'
    document.querySelector('.shippuuden-season-12-table').style.display = 'none'
    document.querySelector('.shippuuden-season-13-table').style.display = 'none'
    document.querySelector('.shippuuden-season-14-table').style.display = 'none'
    document.querySelector('.shippuuden-season-15-table').style.display = 'none'
    document.querySelector('.shippuuden-season-17-table').style.display = 'none'
    document.querySelector('.shippuuden-season-18-table').style.display = 'none'
    document.querySelector('.shippuuden-season-19-table').style.display = 'none'
    document.querySelector('.shippuuden-season-20-table').style.display = 'none'
    document.querySelector('.shippuuden-season-21-table').style.display = 'none'
    document.querySelector('.shippuuden-movies-table').style.display = 'none'
    break;
    case 'ss17':
    document.querySelector('.shippuuden-season-17-table').style.display = 'flex'
    document.querySelector('.shippuuden-season-1-table').style.display = 'none'
    document.querySelector('.shippuuden-season-2-table').style.display = 'none'
    document.querySelector('.shippuuden-season-3-table').style.display = 'none'
    document.querySelector('.shippuuden-season-4-table').style.display = 'none'
    document.querySelector('.shippuuden-season-5-table').style.display = 'none'
    document.querySelector('.shippuuden-season-6-table').style.display = 'none'
    document.querySelector('.shippuuden-season-7-table').style.display = 'none'
    document.querySelector('.shippuuden-season-8-table').style.display = 'none'
    document.querySelector('.shippuuden-season-9-table').style.display = 'none'
    document.querySelector('.shippuuden-season-10-table').style.display = 'none'
    document.querySelector('.shippuuden-season-11-table').style.display = 'none'
    document.querySelector('.shippuuden-season-12-table').style.display = 'none'
    document.querySelector('.shippuuden-season-13-table').style.display = 'none'
    document.querySelector('.shippuuden-season-14-table').style.display = 'none'
    document.querySelector('.shippuuden-season-15-table').style.display = 'none'
    document.querySelector('.shippuuden-season-16-table').style.display = 'none'
    document.querySelector('.shippuuden-season-18-table').style.display = 'none'
    document.querySelector('.shippuuden-season-19-table').style.display = 'none'
    document.querySelector('.shippuuden-season-20-table').style.display = 'none'
    document.querySelector('.shippuuden-season-21-table').style.display = 'none'
    document.querySelector('.shippuuden-movies-table').style.display = 'none'
    break;
    case 'ss18':
    document.querySelector('.shippuuden-season-18-table').style.display = 'flex'
    document.querySelector('.shippuuden-season-1-table').style.display = 'none'
    document.querySelector('.shippuuden-season-2-table').style.display = 'none'
    document.querySelector('.shippuuden-season-3-table').style.display = 'none'
    document.querySelector('.shippuuden-season-4-table').style.display = 'none'
    document.querySelector('.shippuuden-season-5-table').style.display = 'none'
    document.querySelector('.shippuuden-season-6-table').style.display = 'none'
    document.querySelector('.shippuuden-season-7-table').style.display = 'none'
    document.querySelector('.shippuuden-season-8-table').style.display = 'none'
    document.querySelector('.shippuuden-season-9-table').style.display = 'none'
    document.querySelector('.shippuuden-season-10-table').style.display = 'none'
    document.querySelector('.shippuuden-season-11-table').style.display = 'none'
    document.querySelector('.shippuuden-season-12-table').style.display = 'none'
    document.querySelector('.shippuuden-season-13-table').style.display = 'none'
    document.querySelector('.shippuuden-season-14-table').style.display = 'none'
    document.querySelector('.shippuuden-season-15-table').style.display = 'none'
    document.querySelector('.shippuuden-season-16-table').style.display = 'none'
    document.querySelector('.shippuuden-season-17-table').style.display = 'none'
    document.querySelector('.shippuuden-season-19-table').style.display = 'none'
    document.querySelector('.shippuuden-season-20-table').style.display = 'none'
    document.querySelector('.shippuuden-season-21-table').style.display = 'none'
    document.querySelector('.shippuuden-movies-table').style.display = 'none'
    break;
    case 'ss19':
    document.querySelector('.shippuuden-season-19-table').style.display = 'flex'
    document.querySelector('.shippuuden-season-1-table').style.display = 'none'
    document.querySelector('.shippuuden-season-2-table').style.display = 'none'
    document.querySelector('.shippuuden-season-3-table').style.display = 'none'
    document.querySelector('.shippuuden-season-4-table').style.display = 'none'
    document.querySelector('.shippuuden-season-5-table').style.display = 'none'
    document.querySelector('.shippuuden-season-6-table').style.display = 'none'
    document.querySelector('.shippuuden-season-7-table').style.display = 'none'
    document.querySelector('.shippuuden-season-8-table').style.display = 'none'
    document.querySelector('.shippuuden-season-9-table').style.display = 'none'
    document.querySelector('.shippuuden-season-10-table').style.display = 'none'
    document.querySelector('.shippuuden-season-11-table').style.display = 'none'
    document.querySelector('.shippuuden-season-12-table').style.display = 'none'
    document.querySelector('.shippuuden-season-13-table').style.display = 'none'
    document.querySelector('.shippuuden-season-14-table').style.display = 'none'
    document.querySelector('.shippuuden-season-15-table').style.display = 'none'
    document.querySelector('.shippuuden-season-16-table').style.display = 'none'
    document.querySelector('.shippuuden-season-17-table').style.display = 'none'
    document.querySelector('.shippuuden-season-18-table').style.display = 'none'
    document.querySelector('.shippuuden-season-20-table').style.display = 'none'
    document.querySelector('.shippuuden-season-21-table').style.display = 'none'
    document.querySelector('.shippuuden-movies-table').style.display = 'none'
    break;
    case 'ss20':
    document.querySelector('.shippuuden-season-20-table').style.display = 'flex'
    document.querySelector('.shippuuden-season-1-table').style.display = 'none'
    document.querySelector('.shippuuden-season-2-table').style.display = 'none'
    document.querySelector('.shippuuden-season-3-table').style.display = 'none'
    document.querySelector('.shippuuden-season-4-table').style.display = 'none'
    document.querySelector('.shippuuden-season-5-table').style.display = 'none'
    document.querySelector('.shippuuden-season-6-table').style.display = 'none'
    document.querySelector('.shippuuden-season-7-table').style.display = 'none'
    document.querySelector('.shippuuden-season-8-table').style.display = 'none'
    document.querySelector('.shippuuden-season-9-table').style.display = 'none'
    document.querySelector('.shippuuden-season-10-table').style.display = 'none'
    document.querySelector('.shippuuden-season-11-table').style.display = 'none'
    document.querySelector('.shippuuden-season-12-table').style.display = 'none'
    document.querySelector('.shippuuden-season-13-table').style.display = 'none'
    document.querySelector('.shippuuden-season-14-table').style.display = 'none'
    document.querySelector('.shippuuden-season-15-table').style.display = 'none'
    document.querySelector('.shippuuden-season-16-table').style.display = 'none'
    document.querySelector('.shippuuden-season-17-table').style.display = 'none'
    document.querySelector('.shippuuden-season-18-table').style.display = 'none'
    document.querySelector('.shippuuden-season-19-table').style.display = 'none'
    document.querySelector('.shippuuden-season-21-table').style.display = 'none'
    document.querySelector('.shippuuden-movies-table').style.display = 'none'
    break;
    case 'ss21':
    document.querySelector('.shippuuden-season-21-table').style.display = 'flex'
    document.querySelector('.shippuuden-season-1-table').style.display = 'none'
    document.querySelector('.shippuuden-season-2-table').style.display = 'none'
    document.querySelector('.shippuuden-season-3-table').style.display = 'none'
    document.querySelector('.shippuuden-season-4-table').style.display = 'none'
    document.querySelector('.shippuuden-season-5-table').style.display = 'none'
    document.querySelector('.shippuuden-season-6-table').style.display = 'none'
    document.querySelector('.shippuuden-season-7-table').style.display = 'none'
    document.querySelector('.shippuuden-season-8-table').style.display = 'none'
    document.querySelector('.shippuuden-season-9-table').style.display = 'none'
    document.querySelector('.shippuuden-season-10-table').style.display = 'none'
    document.querySelector('.shippuuden-season-11-table').style.display = 'none'
    document.querySelector('.shippuuden-season-12-table').style.display = 'none'
    document.querySelector('.shippuuden-season-13-table').style.display = 'none'
    document.querySelector('.shippuuden-season-14-table').style.display = 'none'
    document.querySelector('.shippuuden-season-15-table').style.display = 'none'
    document.querySelector('.shippuuden-season-16-table').style.display = 'none'
    document.querySelector('.shippuuden-season-17-table').style.display = 'none'
    document.querySelector('.shippuuden-season-18-table').style.display = 'none'
    document.querySelector('.shippuuden-season-19-table').style.display = 'none'
    document.querySelector('.shippuuden-season-20-table').style.display = 'none'
    document.querySelector('.shippuuden-movies-table').style.display = 'none'
    break;
    case 'ssm':
    document.querySelector('.shippuuden-movies-table').style.display = 'flex'
    document.querySelector('.shippuuden-season-1-table').style.display = 'none'
    document.querySelector('.shippuuden-season-2-table').style.display = 'none'
    document.querySelector('.shippuuden-season-3-table').style.display = 'none'
    document.querySelector('.shippuuden-season-4-table').style.display = 'none'
    document.querySelector('.shippuuden-season-5-table').style.display = 'none'
    document.querySelector('.shippuuden-season-6-table').style.display = 'none'
    document.querySelector('.shippuuden-season-7-table').style.display = 'none'
    document.querySelector('.shippuuden-season-8-table').style.display = 'none'
    document.querySelector('.shippuuden-season-9-table').style.display = 'none'
    document.querySelector('.shippuuden-season-10-table').style.display = 'none'
    document.querySelector('.shippuuden-season-11-table').style.display = 'none'
    document.querySelector('.shippuuden-season-12-table').style.display = 'none'
    document.querySelector('.shippuuden-season-13-table').style.display = 'none'
    document.querySelector('.shippuuden-season-14-table').style.display = 'none'
    document.querySelector('.shippuuden-season-15-table').style.display = 'none'
    document.querySelector('.shippuuden-season-16-table').style.display = 'none'
    document.querySelector('.shippuuden-season-17-table').style.display = 'none'
    document.querySelector('.shippuuden-season-18-table').style.display = 'none'
    document.querySelector('.shippuuden-season-19-table').style.display = 'none'
    document.querySelector('.shippuuden-season-20-table').style.display = 'none'
    document.querySelector('.shippuuden-season-21-table').style.display = 'none'
    break;
    default: return;
  }
}
